(()=>{
'use strict';
let BANK=window.QUESTION_BANK||[];
let TOPICS=[];
const LETTERS=['A','B','C','D'];
const CFG=window.APP_CONFIG||{cloudEnabled:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHTML=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const fmtTime=sec=>{sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};
const loadJSON=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}};
const saveJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const authStore='tp.v1.2.auth';
let profileNumber='',profileName='',isAdmin=false,cloudSessionToken='';
let session=null,timer=null,deferredInstall=null,lastResult=null,view='home';
let K_STATS='',K_SESSION='';

function hashId(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function setProfile(mech,name='',admin=false){profileNumber=String(mech);profileName=name||'';isAdmin=!!admin;const h=hashId(profileNumber);K_STATS=`tp.v1.2.stats.${h}`;K_SESSION=`tp.v1.2.session.${h}`;$('#profileBadge').textContent=`N.º ${profileNumber}${isAdmin?' · Admin':''}`;$('#adminBtn')?.classList.toggle('hidden',!isAdmin)}
function validMechanical(v){return /^\d{6}$/.test(String(v||'').trim())}
function validPin(v){return /^\d{4,6}$/.test(String(v||''))}
function emptyStats(){return {byQuestion:{},history:[],bookmarks:[]}}
function getStats(){const s=loadJSON(K_STATS,null);return s&&s.byQuestion?s:emptyStats()}
function saveStats(s){saveJSON(K_STATS,s);if(CFG.cloudEnabled&&cloudSessionToken)cloudPushStats(s).catch(()=>{})}
function qById(id){return BANK.find(q=>q.id===Number(id))}
function questionStat(id){return getStats().byQuestion[String(id)]||{attempts:0,correct:0,wrong:0}}
function recordAnswer(id,ok){const s=getStats(),k=String(id),v=s.byQuestion[k]||{attempts:0,correct:0,wrong:0};v.attempts++;ok?v.correct++:v.wrong++;s.byQuestion[k]=v;saveStats(s)}
function isBookmarked(id){return getStats().bookmarks.includes(Number(id))}
function toggleBookmark(id){const s=getStats(),n=Number(id),i=s.bookmarks.indexOf(n);i>=0?s.bookmarks.splice(i,1):s.bookmarks.push(n);saveStats(s);return i<0}
function weakness(id){const v=questionStat(id);if(!v.attempts)return 0;return v.wrong*4+(v.wrong/v.attempts)*3-v.correct*.05}
function topicMetrics(topic){const qs=BANK.filter(q=>q.topic===topic);let attempts=0,correct=0,wrongQuestions=0,seen=0;const st=getStats().byQuestion;for(const q of qs){const v=st[String(q.id)];if(v){attempts+=v.attempts||0;correct+=v.correct||0;if((v.attempts||0)>0)seen++;if(v.wrong>0)wrongQuestions++}}return {questions:qs.length,attempts,correct,rate:attempts?Math.round(correct/attempts*100):0,wrongQuestions,seen}}
function overallMetrics(){const s=getStats();let attempts=0,correct=0,weak=0,seen=0;Object.values(s.byQuestion).forEach(v=>{attempts+=v.attempts||0;correct+=v.correct||0;if((v.wrong||0)>0)weak++;if((v.attempts||0)>0)seen++});return {attempts,correct,rate:attempts?Math.round(correct/attempts*100):0,weak,seen,coverage:BANK.length?Math.round(seen/BANK.length*100):0,sessions:s.history.length,bookmarks:s.bookmarks.length}}

async function supabaseFetch(path,opts={}){if(!CFG.supabaseUrl||!CFG.supabaseAnonKey)throw new Error('Supabase não configurado.');const url=CFG.supabaseUrl.replace(/\/$/,'')+path;const headers={apikey:CFG.supabaseAnonKey,Authorization:`Bearer ${CFG.supabaseAnonKey}`,'Content-Type':'application/json',...(opts.headers||{})};const res=await fetch(url,{...opts,headers});if(!res.ok)throw new Error((await res.text())||res.statusText);const txt=await res.text();return txt?JSON.parse(txt):null}
async function rpc(name,payload={}){return supabaseFetch(`/rest/v1/rpc/${name}`,{method:'POST',body:JSON.stringify(payload)})}
function serverMessage(code){return ({invalid_number:'O número mecanográfico deve ter exatamente 6 dígitos.',invalid_pin:'O PIN deve ter 4 a 6 dígitos.',invalid_code:'O código de ativação deve ter 8 dígitos.',not_authorized:'Este número não consta da lista de utilizadores autorizados. Contacta o administrador.',inactive:'Este acesso encontra-se bloqueado. Contacta o administrador.',activation_required:'Esta conta ainda não foi ativada. Escolhe “Primeiro acesso / Ativar conta”.',already_activated:'Esta conta já está ativada. Volta ao login normal.',invalid_activation:'Número ou código de ativação incorreto.',wrong_pin:'PIN incorreto.',locked:'Demasiadas tentativas. Aguarda 15 minutos e tenta novamente.',exists:'Esse número já existe na lista.',cannot_reset_self:'Por segurança, não podes repor o teu próprio acesso a partir desta sessão.',cannot_disable_self:'Não podes bloquear a tua própria conta de administrador.',not_found:'Utilizador não encontrado.'}[code]||'Não foi possível concluir a operação.')}
async function cloudLoadQuestions(){const rows=await rpc('api_get_questions',{p_token:cloudSessionToken});if(Array.isArray(rows)&&rows.length)BANK=rows.map(r=>({...r,answers:Array.isArray(r.answers)?r.answers:JSON.parse(r.answers)}));}
async function cloudPullStats(){return rpc('api_get_stats',{p_token:cloudSessionToken})}
async function cloudPushStats(stats){if(!cloudSessionToken)return;return rpc('api_save_stats',{p_token:cloudSessionToken,p_stats:stats})}
async function enterAuthenticated(result){cloudSessionToken=result.token||cloudSessionToken;setProfile(result.mechanical_no,result.display_name,result.is_admin);saveJSON(authStore,{token:cloudSessionToken,mechanical_no:profileNumber});$('#loginMsg').textContent='A carregar banco de perguntas e progresso…';await cloudLoadQuestions();const remote=await cloudPullStats();if(remote?.byQuestion)saveJSON(K_STATS,remote);if(!BANK.length)throw new Error('Banco de perguntas indisponível.');TOPICS=[...new Set(BANK.map(q=>q.topic))];$('#syncStatus').textContent='Progresso sincronizado com a tua conta.';initAfterLogin()}
async function loginUser(){const mech=$('#loginMechanical').value.trim(),pin=$('#loginPin').value;$('#loginMsg').textContent='';if(!validMechanical(mech)){ $('#loginMsg').textContent=serverMessage('invalid_number');return}if(!validPin(pin)){ $('#loginMsg').textContent=serverMessage('invalid_pin');return}try{const r=await rpc('api_login',{p_mechanical:mech,p_pin:pin});if(!r?.ok){$('#loginMsg').textContent=serverMessage(r?.error);return}await enterAuthenticated(r)}catch(e){$('#loginMsg').textContent='Erro de ligação: '+e.message}}
async function activateUser(){const mech=$('#activateMechanical').value.trim(),code=$('#activateCode').value.trim(),pin=$('#activatePin').value,pin2=$('#activatePin2').value;$('#loginMsg').textContent='';if(!validMechanical(mech)){ $('#loginMsg').textContent=serverMessage('invalid_number');return}if(!/^\d{8}$/.test(code)){ $('#loginMsg').textContent=serverMessage('invalid_code');return}if(!validPin(pin)){ $('#loginMsg').textContent=serverMessage('invalid_pin');return}if(pin!==pin2){$('#loginMsg').textContent='Os dois PIN não coincidem.';return}try{const r=await rpc('api_activate',{p_mechanical:mech,p_activation_code:code,p_pin:pin});if(!r?.ok){$('#loginMsg').textContent=serverMessage(r?.error);return}await enterAuthenticated(r)}catch(e){$('#loginMsg').textContent='Erro de ligação: '+e.message}}
async function tryRestoreSession(){const saved=loadJSON(authStore,null);if(!saved?.token)return false;try{cloudSessionToken=saved.token;const r=await rpc('api_session_info',{p_token:cloudSessionToken});if(!r?.ok)throw new Error('invalid');await enterAuthenticated({...r,token:cloudSessionToken});return true}catch{localStorage.removeItem(authStore);cloudSessionToken='';return false}}

function initAfterLogin(){
  $('#loginGate').classList.add('hidden');$('#appShell').classList.remove('hidden');
  fillTopicSelects();$('#bankCount').textContent=BANK.length;bindStaticHandlers();go('home');
}

function go(name){view=name;$$('.view').forEach(v=>v.classList.add('hidden'));$(`#view-${name}`)?.classList.remove('hidden');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===name));document.body.classList.toggle('in-session',name==='session');window.scrollTo({top:0,behavior:'instant'});if(name==='home')renderHome();if(name==='study')renderStudy();if(name==='stats')renderStats();$('#main')?.focus({preventScroll:true})}
function fillTopicSelects(){for(const sel of [$('#configTopic'),$('#studyTopic')]){if(!sel)continue;sel.innerHTML='<option value="all">Todas as matérias</option>'+TOPICS.map(t=>`<option value="${escapeHTML(t)}">${escapeHTML(t)}</option>`).join('')}}

function renderHome(){const m=overallMetrics();$('#homeRate').textContent=m.attempts?`${m.rate}%`:'—';$('#homeAttempts').textContent=m.attempts;$('#coveragePct').textContent=`${m.coverage}%`;$('#homeDial').style.setProperty('--deg',`${m.rate*3.6}deg`);$('#weakLabel').textContent=m.weak?`${m.weak} perguntas com erros`:'Ainda sem erros registados';$('#unseenLabel').textContent=`${Math.max(0,BANK.length-m.seen)} por ver`;$('#topicOverview').innerHTML=TOPICS.map(t=>topicCardHTML(t,topicMetrics(t))).join('');const saved=loadJSON(K_SESSION,null);const rc=$('#resumeCard');if(saved?.items?.length&&!saved.finished){rc.classList.remove('hidden');$('#resumeTitle').textContent=saved.mode==='exam'?'Continuar teste':'Continuar treino';const answered=saved.items.filter(x=>x.selected!==null).length;$('#resumeMeta').textContent=`${answered}/${saved.items.length} respondidas · ${saved.topic==='all'?'Todas as matérias':saved.topic}`}else rc.classList.add('hidden')}
function topicCardHTML(topic,m){const txt=m.attempts?`${m.attempts} respostas · ${m.seen}/${m.questions} vistas · ${m.wrongQuestions} por rever`:`${m.questions} perguntas · ainda sem treino`;return `<article class="topic-card card"><div class="topic-top"><h3>${escapeHTML(topic)}</h3><span class="rate">${m.attempts?m.rate+'%':'—'}</span></div><div class="meter"><span style="width:${m.rate}%"></span></div><small>${txt}</small></article>`}
function openConfig(mode){$('#configMode').value=mode;$('#configTitle').textContent=mode==='exam'?'Configurar simulação':'Configurar treino';$('#smartOnlyRow').classList.toggle('hidden',mode!=='practice');$('#configCount').value=mode==='exam'?'40':'20';$('#configTime').value=mode==='exam'?'3600':'0';$('#configDialog').showModal()}
function startRealExam(){let items=[];for(const t of TOPICS){let p=shuffle(BANK.filter(q=>q.topic===t).slice());items.push(...p.slice(0,5))}items=shuffle(items);startSessionFromQuestions({mode:'exam',topic:'all',timeLimit:3600,shuffleAnswers:true,label:'Teste real'},items)}
function startSession(cfg,customIds=null){let pool=BANK.filter(q=>cfg.topic==='all'||q.topic===cfg.topic);if(customIds)pool=pool.filter(q=>customIds.includes(q.id));if(cfg.smartOnly&&!customIds)pool.sort((a,b)=>weakness(b.id)-weakness(a.id));else if(cfg.shuffleQuestions)shuffle(pool);if(cfg.count!=='all')pool=pool.slice(0,Math.min(Number(cfg.count),pool.length));if(!pool.length){alert('Não há perguntas disponíveis com estes filtros.');return}startSessionFromQuestions(cfg,pool)}
function startSessionFromQuestions(cfg,pool){session={version:1,mode:cfg.mode,topic:cfg.topic||'all',label:cfg.label||'',count:pool.length,timeLimit:cfg.timeLimit||0,shuffleAnswers:cfg.shuffleAnswers!==false,index:0,startedAt:Date.now(),finished:false,items:pool.map(q=>({qid:q.id,order:(()=>{const a=[0,1,2,3];return cfg.shuffleAnswers===false?a:shuffle(a)})(),selected:null,locked:false,committed:false}))};saveSession();beginSession()}
function saveSession(){if(session&&!session.finished)saveJSON(K_SESSION,session)}
function clearSession(){localStorage.removeItem(K_SESSION)}
function beginSession(){go('session');startTimer();renderSession()}
function resumeSession(){const s=loadJSON(K_SESSION,null);if(!s?.items?.length)return;session=s;beginSession()}
function currentItem(){return session.items[session.index]}
function currentQ(){return qById(currentItem().qid)}
function elapsed(){return Math.floor((Date.now()-session.startedAt)/1000)}
function remaining(){return session.timeLimit?session.timeLimit-elapsed():0}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(!session||session.finished)return;renderTimer();if(session.timeLimit&&remaining()<=0)finishSession(true)},500);renderTimer()}
function renderTimer(){const el=$('#sessionTimer');if(!el||!session)return;const val=session.timeLimit?remaining():elapsed();el.textContent=fmtTime(val);el.classList.toggle('warning',session.timeLimit&&val<=600&&val>120);el.classList.toggle('danger',session.timeLimit&&val<=120)}
function renderSession(){if(!session)return;const item=currentItem(),q=currentQ(),answered=session.items.filter(i=>i.selected!==null).length;$('#sessionCounter').textContent=`${session.index+1} / ${session.items.length}`;$('#sessionTopic').textContent=q.topic;$('#progressBar').style.width=`${((session.index+1)/session.items.length)*100}%`;$('#modeBadge').textContent=session.mode==='exam'?'Simulação':'Treino';$('#answeredCount').textContent=`${answered}/${session.items.length}`;$('#questionText').textContent=q.question;$('#bookmarkBtn').textContent=isBookmarked(q.id)?'★':'☆';const box=$('#answers');box.innerHTML='';item.order.forEach((orig,pos)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span class="letter">${LETTERS[pos]}</span><span>${escapeHTML(q.answers[orig])}</span>`;if(item.selected===pos)b.classList.add('selected');if(session.mode==='practice'&&item.locked){if(orig===q.correct)b.classList.add('correct');else if(item.selected===pos)b.classList.add('wrong');else b.classList.add('dim')}b.addEventListener('click',()=>selectAnswer(pos));box.appendChild(b)});renderFeedback();renderQuestionNav();$('#prevBtn').disabled=session.index===0;$('#nextBtn').textContent=session.index===session.items.length-1?'Terminar →':'Seguinte →'}
function selectAnswer(pos){const item=currentItem(),q=currentQ();if(session.mode==='practice'&&item.locked)return;item.selected=pos;if(session.mode==='practice'){item.locked=true;if(!item.committed){recordAnswer(q.id,item.order[pos]===q.correct);item.committed=true}}saveSession();renderSession()}
function renderFeedback(){const f=$('#feedback'),s=$('#sourceBox'),item=currentItem(),q=currentQ();if(session.mode!=='practice'||!item.locked){f.className='feedback hidden';f.textContent='';s.classList.add('hidden');s.textContent='';return}const ok=item.order[item.selected]===q.correct;const correctPos=item.order.indexOf(q.correct);f.className=`feedback ${ok?'good':'bad'}`;f.innerHTML=ok?`✓ Resposta correta.<br><small>${escapeHTML(q.explanation||'')}</small>`:`✕ Resposta errada. Correta: <b>${LETTERS[correctPos]} — ${escapeHTML(q.answers[q.correct])}</b><br><small>${escapeHTML(q.explanation||'')}</small>`;s.classList.remove('hidden');s.innerHTML=`<b>Fonte:</b> ${escapeHTML(q.source||'Material fornecido')}`}
function renderQuestionNav(){const nav=$('#questionNav');nav.innerHTML='';session.items.forEach((it,i)=>{const q=qById(it.qid),b=document.createElement('button');b.textContent=i+1;if(it.selected!==null)b.classList.add('answered');if(i===session.index)b.classList.add('current');if(session.mode==='practice'&&it.locked)b.classList.add(it.order[it.selected]===q.correct?'correct':'wrong');b.addEventListener('click',()=>{session.index=i;saveSession();renderSession()});nav.appendChild(b)})}
function finishSession(auto=false){if(!session||session.finished)return;const blank=session.items.filter(i=>i.selected===null).length;if(!auto&&session.mode==='exam'&&blank&&!confirm(`Tens ${blank} pergunta(s) por responder. Queres terminar na mesma?`))return;session.finished=true;clearInterval(timer);if(session.mode==='exam'){for(const it of session.items){if(it.selected!==null&&!it.committed){const q=qById(it.qid);recordAnswer(q.id,it.order[it.selected]===q.correct);it.committed=true}}}const correct=session.items.filter(it=>it.selected!==null&&it.order[it.selected]===qById(it.qid).correct).length;const wrong=session.items.filter(it=>it.selected!==null&&it.order[it.selected]!==qById(it.qid).correct).length;const total=session.items.length,pct=Math.round(correct/total*100);lastResult={...session,correct,wrong,blank,total,pct,elapsed:elapsed(),auto};const st=getStats();st.history.unshift({date:new Date().toISOString(),mode:session.mode,topic:session.topic,label:session.label||'',total,correct,wrong,blank,pct,elapsed:lastResult.elapsed});st.history=st.history.slice(0,50);saveStats(st);clearSession();showResults()}
function showResults(){go('results');const r=lastResult;if(!r)return;$('#resultPct').textContent=`${r.pct}%`;$('#resultDial').style.setProperty('--deg',`${r.pct*3.6}deg`);$('#resultTitle').textContent=r.auto?'Tempo terminado':'Sessão concluída';$('#resultMeta').textContent=`${r.label|| (r.mode==='exam'?'Simulação':'Treino')} · ${r.topic==='all'?'Todas as matérias':r.topic} · ${fmtTime(r.elapsed)}`;$('#resultCorrect').textContent=r.correct;$('#resultWrong').textContent=r.wrong;$('#resultBlank').textContent=r.blank;const ids=r.items.filter(it=>it.selected===null||it.order[it.selected]!==qById(it.qid).correct).map(it=>it.qid);$('#retryWrongBtn').disabled=!ids.length;$('#retryWrongBtn').dataset.ids=ids.join(',');$('#reviewFilter').value='all';renderReview('all')}
function renderReview(filter){if(!lastResult)return;const list=$('#reviewList');list.innerHTML='';lastResult.items.forEach((it,i)=>{const q=qById(it.qid),ok=it.selected!==null&&it.order[it.selected]===q.correct;if(filter==='wrong'&&ok)return;if(filter==='correct'&&!ok)return;const chosen=it.selected===null?null:q.answers[it.order[it.selected]];const correct=q.answers[q.correct];const d=document.createElement('article');d.className='review-item';d.innerHTML=`<span class="eyebrow">${escapeHTML(q.topic)} · ${escapeHTML(q.subtopic||'')}</span><h3>${i+1}. ${escapeHTML(q.question)}</h3><p class="${ok?'good-text':'bad-text'}"><b>A tua resposta:</b> ${chosen?escapeHTML(chosen):'Em branco'}</p><p class="good-text"><b>Correta:</b> ${escapeHTML(correct)}</p><p>${escapeHTML(q.explanation||'')}</p><p class="muted"><b>Fonte:</b> ${escapeHTML(q.source||'')}</p>`;list.appendChild(d)});if(!list.children.length)list.innerHTML='<div class="library-item"><p>Não há perguntas neste filtro.</p></div>'}

function renderStudy(){renderQuestionLibrary();renderBookmarks()}
function renderQuestionLibrary(){const query=$('#searchQuestions').value.trim().toLowerCase(),topic=$('#studyTopic').value;const list=BANK.filter(q=>(topic==='all'||q.topic===topic)&&(!query||[q.question,...q.answers,q.source,q.subtopic].join(' ').toLowerCase().includes(query)));const box=$('#questionLibrary');box.innerHTML=list.map(q=>libraryItemHTML(q)).join('')||'<div class="library-item"><p>Nenhum resultado.</p></div>';bindLibraryButtons(box)}
function libraryItemHTML(q){return `<article class="library-item"><div><span class="eyebrow">${escapeHTML(q.topic)} · ${escapeHTML(q.subtopic||'')}</span><h3>${escapeHTML(q.question)}</h3><div class="answer-reveal hidden" id="reveal-${q.id}"><p class="good-text"><b>Resposta correta:</b> ${escapeHTML(q.answers[q.correct])}</p><p>${escapeHTML(q.explanation||'')}</p><p class="muted"><b>Fonte:</b> ${escapeHTML(q.source||'')}</p></div><div class="meta"><span class="chip">Questão ${q.id}</span><span class="chip">Dificuldade ${q.difficulty||2}/3</span></div></div><div class="library-actions"><button class="small-btn reveal-btn" data-id="${q.id}">Resposta</button><button class="small-btn mark-btn" data-id="${q.id}">${isBookmarked(q.id)?'★':'☆'}</button></div></article>`}
function bindLibraryButtons(root){root.querySelectorAll('.reveal-btn').forEach(b=>b.onclick=()=>root.querySelector(`#reveal-${b.dataset.id}`)?.classList.toggle('hidden'));root.querySelectorAll('.mark-btn').forEach(b=>b.onclick=()=>{toggleBookmark(Number(b.dataset.id));renderQuestionLibrary();renderBookmarks()})}
function renderBookmarks(){const ids=getStats().bookmarks;const qs=ids.map(qById).filter(Boolean);const box=$('#bookmarkLibrary');box.innerHTML=qs.map(q=>libraryItemHTML(q)).join('')||'<div class="library-item"><p>Ainda não marcaste perguntas.</p></div>';bindLibraryButtons(box)}
function renderStats(){const m=overallMetrics(),s=getStats();$('#statAttempts').textContent=m.attempts;$('#statRate').textContent=m.attempts?`${m.rate}%`:'0%';$('#statSessions').textContent=m.sessions;$('#statCoverage').textContent=`${m.coverage}%`;$('#topicStats').innerHTML=TOPICS.map(t=>topicCardHTML(t,topicMetrics(t))).join('');const weak=BANK.filter(q=>questionStat(q.id).wrong>0).sort((a,b)=>weakness(b.id)-weakness(a.id)).slice(0,16);$('#weakList').innerHTML=weak.map(q=>{const v=questionStat(q.id);return `<article class="library-item"><div><span class="eyebrow">${escapeHTML(q.topic)}</span><h3>${escapeHTML(q.question)}</h3><p>${v.wrong} erro(s) · ${v.correct} acerto(s) · ${v.attempts} tentativa(s)</p></div><div class="library-actions"><button class="small-btn weak-train" data-id="${q.id}">Treinar</button></div></article>`}).join('')||'<div class="library-item"><p>Ainda não há erros registados.</p></div>';$('#weakList').querySelectorAll('.weak-train').forEach(b=>b.onclick=()=>startSession({mode:'practice',topic:'all',count:'all',timeLimit:0,shuffleQuestions:false,shuffleAnswers:true},[Number(b.dataset.id)]));$('#historyList').innerHTML=s.history.map(h=>`<article class="history-item"><div><strong>${escapeHTML(h.label|| (h.mode==='exam'?'Simulação':'Treino'))} · ${h.topic==='all'?'Todas':escapeHTML(h.topic)}</strong><small>${new Date(h.date).toLocaleString('pt-PT')} · ${h.correct}/${h.total} certas · ${fmtTime(h.elapsed)}</small></div><div class="history-score">${h.pct}%</div></article>`).join('')||'<div class="history-item"><small>Ainda não concluíste sessões.</small></div>'}


function exportStats(){const payload={app:'Treino Técnico-Policial',version:'1.2',mechanical_no:profileNumber,exportedAt:new Date().toISOString(),stats:getStats()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`progresso-treino-${profileNumber}.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
async function importStats(file){try{const obj=JSON.parse(await file.text());const incoming=obj.stats||obj;if(!incoming?.byQuestion)throw new Error('Ficheiro inválido');if(confirm('Substituir o progresso atual pelo progresso deste ficheiro?')){saveStats(incoming);renderStats();renderHome();alert('Progresso importado e sincronizado.')}}catch(e){alert('Não foi possível importar: '+e.message)}}

async function renderAdmin(){if(!isAdmin)return;const box=$('#adminUsers');box.innerHTML='<div class="library-item"><p>A carregar…</p></div>';try{const users=await rpc('api_admin_list_users',{p_token:cloudSessionToken});box.innerHTML=(users||[]).map(u=>`<article class="admin-user"><div><strong>${escapeHTML(u.mechanical_no)}${u.display_name?' · '+escapeHTML(u.display_name):''}</strong><small>${u.last_login_at?'Último acesso: '+new Date(u.last_login_at).toLocaleString('pt-PT'):'Ainda sem acesso'}</small><div class="admin-badges"><span class="admin-badge ${u.active?'ok':'off'}">${u.active?'Ativo':'Bloqueado'}</span><span class="admin-badge ${u.activated?'ok':''}">${u.activated?'Ativado':'Por ativar'}</span>${u.is_admin?'<span class="admin-badge">Admin</span>':''}</div></div><div class="admin-user-actions">${u.mechanical_no!==profileNumber?`<button class="small-btn admin-toggle" data-id="${u.mechanical_no}" data-active="${u.active?'0':'1'}">${u.active?'Bloquear':'Ativar'}</button><button class="small-btn admin-reset" data-id="${u.mechanical_no}">Repor PIN</button>`:''}</div></article>`).join('')||'<div class="library-item"><p>Sem utilizadores.</p></div>';box.querySelectorAll('.admin-toggle').forEach(b=>b.onclick=async()=>{const desired=b.dataset.active==='1';const r=await rpc('api_admin_set_active',{p_token:cloudSessionToken,p_mechanical:b.dataset.id,p_active:desired});if(!r?.ok)alert(serverMessage(r?.error));await renderAdmin()});box.querySelectorAll('.admin-reset').forEach(b=>b.onclick=async()=>{if(!confirm(`Repor o PIN do utilizador ${b.dataset.id}? O acesso atual será terminado.`))return;const r=await rpc('api_admin_reset_access',{p_token:cloudSessionToken,p_mechanical:b.dataset.id});if(r?.ok){showGeneratedCode(r.mechanical_no,r.activation_code,'PIN reposto')}else alert(serverMessage(r?.error));await renderAdmin()})}catch(e){box.innerHTML=`<div class="library-item"><p>Erro: ${escapeHTML(e.message)}</p></div>`}}
function showGeneratedCode(mech,code,label='Utilizador adicionado'){const el=$('#adminGeneratedCode');el.classList.remove('hidden');el.innerHTML=`<b>${escapeHTML(label)} — N.º ${escapeHTML(mech)}</b><br>Código de ativação: <code>${escapeHTML(code)}</code><br><small>Entrega este código ao utilizador. É de utilização única.</small>`}
async function addAdminUser(){const mech=$('#adminNewMechanical').value.trim(),name=$('#adminNewName').value.trim();if(!validMechanical(mech)){alert(serverMessage('invalid_number'));return}try{const r=await rpc('api_admin_add_user',{p_token:cloudSessionToken,p_mechanical:mech,p_display_name:name||null});if(!r?.ok){alert(serverMessage(r?.error));return}$('#adminNewMechanical').value='';$('#adminNewName').value='';showGeneratedCode(r.mechanical_no,r.activation_code);await renderAdmin()}catch(e){alert('Erro: '+e.message)}}

let bound=false;
function bindStaticHandlers(){if(bound)return;bound=true;
  $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
  $$('[data-start-mode]').forEach(b=>b.addEventListener('click',()=>openConfig(b.dataset.startMode)));
  $$('[data-open-config]').forEach(b=>b.addEventListener('click',()=>openConfig(b.dataset.openConfig)));
  $('#realExamBtn').onclick=startRealExam;$('#realExamQuick').onclick=startRealExam;
  $('#startConfiguredBtn').onclick=()=>{const cfg={mode:$('#configMode').value,topic:$('#configTopic').value,count:$('#configCount').value,timeLimit:Number($('#configTime').value),shuffleQuestions:$('#shuffleQuestions').checked,shuffleAnswers:$('#shuffleAnswers').checked,smartOnly:$('#smartOnly').checked};$('#configDialog').close();startSession(cfg)};
  $('#resumeBtn').onclick=resumeSession;$('#discardResumeBtn').onclick=()=>{if(confirm('Descartar a sessão guardada?')){clearSession();renderHome()}};
  $('#bookmarkBtn').onclick=()=>{toggleBookmark(currentQ().id);renderSession()};
  $('#prevBtn').onclick=()=>{if(session.index>0){session.index--;saveSession();renderSession()}};
  $('#nextBtn').onclick=()=>{if(session.index<session.items.length-1){session.index++;saveSession();renderSession()}else finishSession(false)};
  $('#finishSessionBtn').onclick=()=>finishSession(false);$('#exitSessionBtn').onclick=()=>{saveSession();clearInterval(timer);go('home')};
  $('#reviewFilter').onchange=e=>renderReview(e.target.value);
  $('#retryWrongBtn').onclick=()=>{const ids=$('#retryWrongBtn').dataset.ids.split(',').filter(Boolean).map(Number);if(ids.length)startSession({mode:'practice',topic:'all',count:'all',timeLimit:0,shuffleQuestions:true,shuffleAnswers:true},ids)};
  $('#smartPracticeBtn').onclick=()=>{const ids=BANK.filter(q=>questionStat(q.id).wrong>0).sort((a,b)=>weakness(b.id)-weakness(a.id)).map(q=>q.id);if(!ids.length){alert('Ainda não tens perguntas erradas.');return}startSession({mode:'practice',topic:'all',count:'all',timeLimit:0,shuffleQuestions:false,shuffleAnswers:true},ids.slice(0,30))};
  $('#unseenPracticeBtn').onclick=()=>{const ids=BANK.filter(q=>questionStat(q.id).attempts===0).map(q=>q.id);if(!ids.length){alert('Já viste todas as perguntas do banco.');return}shuffle(ids);startSession({mode:'practice',topic:'all',count:'all',timeLimit:0,shuffleQuestions:false,shuffleAnswers:true},ids.slice(0,30))};
  $('#searchQuestions').oninput=renderQuestionLibrary;$('#studyTopic').onchange=renderQuestionLibrary;
  $$('[data-study-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-study-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#studyQuestions').classList.toggle('hidden',b.dataset.studyTab!=='questions');$('#studyBookmarks').classList.toggle('hidden',b.dataset.studyTab!=='bookmarks');if(b.dataset.studyTab==='bookmarks')renderBookmarks()}));
  $('#resetAllBtn').onclick=()=>{if(confirm('Apagar estatísticas, histórico, marcadores e sessão deste utilizador em todos os dispositivos?')){const fresh=emptyStats();saveStats(fresh);localStorage.removeItem(K_SESSION);renderStats();renderHome()}};
  $('#exportStatsBtn').onclick=exportStats;$('#importStatsBtn').onclick=()=>$('#importStatsFile').click();$('#importStatsFile').onchange=e=>{if(e.target.files?.[0])importStats(e.target.files[0]);e.target.value=''};
  $('#logoutBtn').onclick=async()=>{clearInterval(timer);try{if(cloudSessionToken)await rpc('api_logout',{p_token:cloudSessionToken})}catch{}localStorage.removeItem(authStore);cloudSessionToken='';location.reload()};
  $('#adminBtn').onclick=async()=>{$('#adminGeneratedCode').classList.add('hidden');$('#adminDialog').showModal();await renderAdmin()};$('#closeAdmin').onclick=()=>$('#adminDialog').close();$('#adminRefreshBtn').onclick=renderAdmin;$('#adminAddBtn').onclick=addAdminUser;
  $('#installBtn').onclick=()=>$('#installDialog').showModal();$('#closeInstall').onclick=()=>$('#installDialog').close();$('#nativeInstallBtn').onclick=async()=>{if(!deferredInstall)return;$('#installDialog').close();deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#nativeInstallBtn').classList.add('hidden')};
  window.addEventListener('keydown',e=>{if(view!=='session'||!session)return;if(['1','2','3','4'].includes(e.key))selectAnswer(Number(e.key)-1);else if(e.key==='ArrowLeft'&&session.index>0){session.index--;saveSession();renderSession()}else if(e.key==='ArrowRight'&&session.index<session.items.length-1){session.index++;saveSession();renderSession()}});
}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#nativeInstallBtn')?.classList.remove('hidden')});
function updateNetwork(){const b=$('#offlineBadge');if(!b)return;b.textContent=navigator.onLine?'● Sincronização online':'● Sem ligação'}
window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});

$('#loginBtn').addEventListener('click',loginUser);$('#loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')loginUser()});
$('#showActivateBtn').onclick=()=>{$('#loginPanel').classList.add('hidden');$('#activatePanel').classList.remove('hidden');$('#activateMechanical').value=$('#loginMechanical').value;$('#loginMsg').textContent=''};
$('#showLoginBtn').onclick=()=>{$('#activatePanel').classList.add('hidden');$('#loginPanel').classList.remove('hidden');$('#loginMechanical').value=$('#activateMechanical').value;$('#loginMsg').textContent=''};
$('#activateBtn').onclick=activateUser;$('#activatePin2').addEventListener('keydown',e=>{if(e.key==='Enter')activateUser()});
(async()=>{if(!CFG.cloudEnabled){$('#loginMsg').textContent='Esta versão requer ligação ao Supabase.';return}await tryRestoreSession()})();
})();
